# Generated by Django 4.2.2 on 2023-08-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('complaint_text', models.TextField()),
                ('complaint_status', models.CharField(default='Pending', max_length=30)),
                ('booked_on', models.DateField()),
                ('expected_returndate', models.DateField()),
                ('total', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServicehubReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_address', models.TextField()),
                ('district', models.CharField(max_length=30)),
                ('hub_image', models.ImageField(upload_to='')),
                ('hub_licence', models.FileField(upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.brand')),
                ('srvicehub_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Troubleshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30, null=True)),
                ('reply', models.CharField(max_length=30, null=True)),
                ('servicehub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Serviceproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('servicehub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_desc', models.TextField()),
                ('servicehub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=30)),
                ('servicehub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRequire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_desc', models.TextField()),
                ('require_price', models.CharField(max_length=30)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='servicehub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='serviceproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.serviceproducts'),
        ),
    ]
