# Generated by Django 4.2.2 on 2023-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0004_remove_complaint_expected_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='user_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='user_phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
