# Generated by Django 4.2.2 on 2023-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0006_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='booked_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='total',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
