# Generated by Django 4.2.2 on 2023-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0007_alter_complaint_booked_on_alter_complaint_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleshoot',
            name='reply',
        ),
        migrations.AddField(
            model_name='troubleshoot',
            name='chatdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
