# Generated by Django 4.2.2 on 2023-08-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0008_remove_troubleshoot_reply_troubleshoot_chatdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshoot',
            name='chatdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
