# Generated by Django 4.2.2 on 2023-08-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0010_alter_troubleshoot_chatdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshoot',
            name='chatdate',
            field=models.DateTimeField(null=True),
        ),
    ]
