# Generated by Django 4.2.2 on 2023-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0011_alter_troubleshoot_chatdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshoot',
            name='sendby',
            field=models.CharField(default='user', max_length=30, null=True),
        ),
    ]
