# Generated by Django 4.2.2 on 2023-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0012_troubleshoot_sendby'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completed_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='paid_on',
            field=models.DateField(null=True),
        ),
    ]
