# Generated by Django 4.2.2 on 2023-08-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0014_complaint_payment_status_complaint_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.complaint'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
