# Generated by Django 4.2.2 on 2023-08-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0015_remove_feedback_hub_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
