# Generated by Django 4.2.2 on 2023-08-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0016_complaint_feedback_desc_complaint_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='feedback_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
