# Generated by Django 4.2.2 on 2023-08-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0018_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehubreg',
            name='brand',
        ),
        migrations.CreateModel(
            name='HubBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.brand')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.servicehubreg')),
            ],
        ),
    ]
