# Generated by Django 4.2.2 on 2023-08-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub_app', '0019_remove_servicehubreg_brand_hubbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproducts',
            name='hub',
        ),
        migrations.AddField(
            model_name='serviceproducts',
            name='hubbrands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicehub_app.hubbrands'),
        ),
    ]
